Resources:
  acmCtRootCA:
    Type: AWS::ACMPCA::CertificateAuthority
    Properties:
      KeyAlgorithm: RSA_2048
      SigningAlgorithm: SHA256WITHRSA
      Subject:
        CommonName: AcmPcaColorTeller
      Type: ROOT
    Metadata:
      aws:cdk:path: acm/acmCtRootCA
  acmGwCA:
    Type: AWS::ACMPCA::CertificateAuthority
    Properties:
      KeyAlgorithm: RSA_2048
      SigningAlgorithm: SHA256WITHRSA
      Subject:
        CommonName: AcmPcaColorGateway
      Type: ROOT
    Metadata:
      aws:cdk:path: acm/acmGwCA
  acmCtRootCert:
    Type: AWS::ACMPCA::Certificate
    Properties:
      CertificateAuthorityArn:
        Fn::GetAtt:
          - acmCtRootCA
          - Arn
      CertificateSigningRequest:
        Fn::GetAtt:
          - acmCtRootCA
          - CertificateSigningRequest
      SigningAlgorithm: SHA256WITHRSA
      Validity:
        Type: YEARS
        Value: 10
      TemplateArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - :acm-pca:::template/RootCACertificate/V1
    Metadata:
      aws:cdk:path: acm/acmCtRootCert
  acmGwCert:
    Type: AWS::ACMPCA::Certificate
    Properties:
      CertificateAuthorityArn:
        Fn::GetAtt:
          - acmGwCA
          - Arn
      CertificateSigningRequest:
        Fn::GetAtt:
          - acmGwCA
          - CertificateSigningRequest
      SigningAlgorithm: SHA256WITHRSA
      Validity:
        Type: YEARS
        Value: 10
      TemplateArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - :acm-pca:::template/RootCACertificate/V1
    Metadata:
      aws:cdk:path: acm/acmGwCert
  acmRootActvn:
    Type: AWS::ACMPCA::CertificateAuthorityActivation
    Properties:
      Certificate:
        Fn::GetAtt:
          - acmCtRootCert
          - Certificate
      CertificateAuthorityArn:
        Fn::GetAtt:
          - acmCtRootCA
          - Arn
      Status: ACTIVE
    Metadata:
      aws:cdk:path: acm/acmRootActvn
  acmGwActvn:
    Type: AWS::ACMPCA::CertificateAuthorityActivation
    Properties:
      Certificate:
        Fn::GetAtt:
          - acmGwCert
          - Certificate
      CertificateAuthorityArn:
        Fn::GetAtt:
          - acmGwCA
          - Arn
      Status: ACTIVE
    Metadata:
      aws:cdk:path: acm/acmGwActvn
  acmCtEndpt65E1B1EC:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: colorteller.mtls.svc.cluster.local
      CertificateAuthorityArn:
        Fn::GetAtt:
          - acmCtRootCA
          - Arn
    Metadata:
      aws:cdk:path: acm/acmCtEndpt/Resource
  acmGwEndpt3683A56B:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: colorgateway.mtls.svc.cluster.local
      CertificateAuthorityArn:
        Fn::GetAtt:
          - acmGwCA
          - Arn
    Metadata:
      aws:cdk:path: acm/acmGwEndpt/Resource
  acmSecretED90EA4E:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        GenerateStringKey: Passphrase
        SecretStringTemplate: '{"GatewayCertificate":"tempcert","GatewayCertificateChain":"tempcertchain","GatewayPrivateKey":"privatekey","Passphrase":"passphrase"}'
      Name: cert-secret
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: acm/acmSecret/Resource
  acmLambdaCertRoleFD04CE4B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCertificateManagerFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
    Metadata:
      aws:cdk:path: acm/acmLambdaCertRole/Resource
  acmInitCertFunc711F4952:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: ef9c64013824812ec8b5cac941d25676b9c16ccbe319b0925f151986ee3ea0a3.zip
      Role:
        Fn::GetAtt:
          - acmLambdaCertRoleFD04CE4B
          - Arn
      Environment:
        Variables:
          COLOR_GATEWAY_ACM_ARN:
            Ref: acmGwEndpt3683A56B
          COLOR_TELLER_ACM_ARN:
            Ref: acmCtEndpt65E1B1EC
          COLOR_TELLER_ACM_PCA_ARN:
            Fn::GetAtt:
              - acmCtRootCA
              - Arn
          COLOR_GATEWAY_ACM_PCA_ARN:
            Fn::GetAtt:
              - acmGwCA
              - Arn
          AWS_ACCOUNT: "644796087233"
          SECRET:
            Ref: acmSecretED90EA4E
      Handler: initcert.lambda_handler
      Runtime: python3.9
      Timeout: 900
    DependsOn:
      - acmLambdaCertRoleFD04CE4B
    Metadata:
      aws:cdk:path: acm/acmInitCertFunc/Resource
      aws:asset:path: asset.ef9c64013824812ec8b5cac941d25676b9c16ccbe319b0925f151986ee3ea0a3
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/3VQwU7DMAz9Fu6pge0A124SZ9R9wOS5XvHaJChxhlDUfydpNRCHnZ79nt+z5Q1sXuDpAb9iQ/3YTHKCfFCk0RTqmJHsJyHk/dntOaichVC5Tfrhg+i3+c+bO2MtqVxRxbvZ0J9u0eHAAfJ7qDLfT5pNZAqs8ddyWPo6tlazEbSQOz8t3oqzmdCe+nL9W3JUt1flVpfI7RFjLKHQVig97BKNrDuMxdxx9CkQm0UtPxnEDUv2Tag3etfLGud8z3CJj9fnV9iWl16iSBOSU7EM3Yo/2WV63G4BAAA=
    Metadata:
      aws:cdk:path: acm/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

