apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualnodes.appmesh.k8s.aws
spec:
  group: appmesh.k8s.aws
  versions:
    - name: v1beta1
      served: true
      storage: true
    - name: v1alpha1
      served: true
      storage: false
  version: v1beta1
  scope: Namespaced
  names:
    plural: virtualnodes
    singular: virtualnode
    kind: VirtualNode
    categories:
      - all
      - appmesh
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required:
        - spec
      properties:
        spec:
          required:
            - meshName
          properties:
            meshName:
              type: string
            listeners:
              type: array
              items:
                type: object
                properties:
                  portMapping:
                    properties:
                      port:
                        type: integer
                      protocol:
                        type: string
                        enum:
                          - tcp
                          - http
            serviceDiscovery:
              type: object
              properties:
                dns:
                  type: object
                  properties:
                    hostName:
                      type: string
            backends:
              type: array
              items:
                oneOf:
                  - type: object
                    properties:
                      backendService:
                        type: object
                        properties:
                          name:
                            type: string
        status:
          properties:
            meshArn:
              type: string
            virtualNodeArn:
              type: string
            cloudMapServiceArn:
              type: string
            queryParameters:
              type: string
            conditions:
              type: array
              items:
                type: object
                required:
                  - type
                properties:
                  type:
                    type: string
                    enum:
                      - VirtualNodeActive
                      - MeshMarkedForDeletion
                  status:
                    type: string
                    enum:
                      - "True"
                      - "False"
                      - Unknown
                  lastTransitionTime:
                    type: string
                  reason:
                    type: string
                  message:
                    type: string
