Parameters:

  FrontendImageName:
    Description: The name for the gateway image
    Type: String

  ColorTellerImageName:
    Description: The name for the color teller image
    Type: String


Resources:
  FrontendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref FrontendImageName

  ColorTellerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ColorTellerImageName
