Database:
  Name: database
  Image: "mongo"
  ImageTag: "3.4"
  Replicas: 1
  Component: "database"
  ServicePort: 27017
  ContainerPort: 27017
  ContainerPortName: database
Queue:
  Name: queue
  Image: "redis"
  ImageTag: "3.2"
  Replicas: 1
  Component: "queue"
  ServicePort: 6379
  ContainerPort: 6379
  ContainerPortName: queue
Vote:
  Name: vote
  Image: "subfuzion/vote-api"
  ImageTag: "latest"
  Replicas: 1
  Component: "vote"
  ServicePort: 80
  ServiceType: LoadBalancer
  ContainerPort: 3000
  ContainerPortName: vote
Worker:
  Name: worker
  Image: "subfuzion/vote-worker"
  ImageTag: "latest"
  Replicas: 1
  Component: "worker"
