---
version: 0.2
phases:
  pre_build:
    commands:
      - SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - REPOSITORY="$DOCKER_REGISTRY_URI:$(date +%Y-%m-%d_%H.%M.%S).$SHA"
      - docker login -u srinivasdevops87 -p Srinivas123$
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build --tag $REPOSITORY .
  post_build:
    commands:
      - docker push $REPOSITORY
      - cat specfiles/deploy.json | jq --arg SHA "$SHA" '. + {"Sha":$SHA}' > tmp.json && mv tmp.json specfiles/deploy.json
      - cat specfiles/deploy.json | jq --arg REPOSITORY "$REPOSITORY" '. + {"ContainerImage":$REPOSITORY}' > tmp.json && mv tmp.json specfiles/deploy.json
      - cat specfiles/deploy.json | jq --arg CONFIG_FILE "$(base64 specfiles/canary-helper.yaml)" '. + {"CanaryTemplate":$CONFIG_FILE}' > tmp.json && mv tmp.json specfiles/deploy.json
      - cat specfiles/deploy.json
artifacts:
  files:
    - specfiles/deploy.json
  discard-paths: yes
