apiVersion: v1
kind: Service
metadata:
  name: jazz
  namespace: prod
  labels:
    app: jazz
spec:
  ports:
  - port: 9080
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: metal
  namespace: prod
  labels:
    app: metal
spec:
  ports:
  - port: 9080
    name: http
