{
 "title": "Lattice-Grafana",
 "description": "Envoy proxy monitoring Dashboard with cluster and host level templates. ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Service",
    "query": "label_values(envoy_cluster_upstream_cx_total, envoy_cluster_name)"
   },
   {
    "name": "hosts",
    "label": "Hosts",
    "query": "label_values(envoy_cluster_upstream_cx_total{envoy_cluster_name=\"$cluster\"}, host)"
   }
  ]
 },
 "panels": [
  { "title": "Server Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Live servers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(envoy_server_live)" }
   ]
  },
  {
   "title": "Cluster State",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total)-sum(envoy_cluster_membership_healthy)) == bool 0"
    }
   ]
  },
  {
   "title": "Unhealthy Clusters",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy)  - sum(envoy_cluster_membership_total))"
    }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(envoy_server_uptime)" }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated)"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size)"
    }
   ]
  },
  { "title": "Requests/Response Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_external_upstream_rq_completed{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\"})"
    }
   ]
  },
  {
   "title": "Response - 2xx",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_external_upstream_rq{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\",envoy_response_code=\"200\"})"
    }
   ]
  },
  {
   "title": "Success Rate (non 5xx)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - (1 - (sum(envoy_cluster_external_upstream_rq{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\",envoy_response_code=\"200\"})/sum(envoy_cluster_external_upstream_rq{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\",envoy_response_code=~\".*\"})))"
    }
   ]
  },
  {
   "title": "Response - 3xx",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_external_upstream_rq{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\",envoy_response_code=~\"3.*\"})"
    }
   ]
  },
  {
   "title": "Response - 4xx",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_external_upstream_rq{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\",envoy_response_code=~\"4.*\"})"
    }
   ]
  },
  {
   "title": "Response - 5xx",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(envoy_cluster_external_upstream_rq{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\",envoy_response_code=~\"5.*\"})"
    }
   ]
  },
  { "title": "Network Traffic Patterns", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Egress CPS / RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{envoy_cluster_name=~\"$cluster\"}[10s]))",
     "legendFormat": "egress CPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\"}[10s]))",
     "legendFormat": "egress RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=~\"$cluster\"}[10s]))",
     "legendFormat": "pending req to"
    },
    {
     "expr": "sum(rate(envoy_cluster_lb_healthy_panic{envoy_cluster_name=~\"$cluster\"}[10s]))",
     "legendFormat": "lb healthy panic RPS"
    }
   ]
  },
  {
   "title": "Upstream Requests (rate/30s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\"}[30s])",
     "legendFormat": "\"$cluster\""
    }
   ]
  },
  {
   "title": "Upstream Connection Summary",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{envoy_cluster_name=~\"$cluster\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_active{envoy_cluster_name=~\"$cluster\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_active{envoy_cluster_name=~\"$cluster\"})",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Global Downstream Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[10s]))",
     "legendFormat": "Globlal RPS"
    },
    {
     "expr": "sum(rate(envoy_http_rq_total[10s]))",
     "legendFormat": "Global Routed RPS"
    }
   ]
  },
  {
   "title": "Network Traffic Details (in bytes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "Upstream - Sent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 34 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Upstream - Sent Buffered",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 34 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_tx_bytes_buffered{envoy_cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Upstream - Received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 34 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Upstream - Received Buffered",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 34 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_rx_bytes_buffered{envoy_cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Downstream Global - Sent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 37 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_tx_bytes_total)"
    }
   ]
  },
  {
   "title": "Downstream Global - Sent Buffered",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 37 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_tx_bytes_buffered)"
    }
   ]
  },
  {
   "title": "Downstream Global - Received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 37 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_rx_bytes_total)"
    }
   ]
  },
  {
   "title": "Downstream Global - Received Buffered",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 37 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_rx_bytes_buffered)"
    }
   ]
  },
  {
   "title": "Upstream Network Traffic (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\"}[10s])",
     "legendFormat": "\"$cluster\"-received"
    },
    {
     "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\"}[10s])",
     "legendFormat": "\"$cluster\"-sent"
    }
   ]
  },
  {
   "title": "Downstream Network Traffic (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_http_downstream_cx_rx_bytes_total{}[10s])",
     "legendFormat": "\"$cluster\" - received"
    },
    {
     "expr": "irate(envoy_http_downstream_cx_tx_bytes_total{}[10s])",
     "legendFormat": "\"$cluster\"- sent"
    }
   ]
  }
 ]
}