Parameters:
  ProjectName:
    Type: String
    Description: Project name to link stacks

Resources:
  Mesh:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Sub '${ProjectName}-mesh'

  GatewayNode:
    Type: AWS::AppMesh::VirtualNode
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualNodeName: gateway
      Spec:
        Backends:
        - VirtualService:
            VirtualServiceName: !Sub 'backend.${ProjectName}.local'
        Listeners:
        - PortMapping:
            Port: 80
            Protocol: http
        ServiceDiscovery:
          DNS:
            Hostname: !Sub "gateway.${ProjectName}.local"

  BackendNode:
    Type: AWS::AppMesh::VirtualNode
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualNodeName: backend-1
      Spec:
        Listeners:
        - PortMapping:
            Port: 80
            Protocol: http
        ServiceDiscovery:
          DNS:
            Hostname: !Sub "backend.${ProjectName}.local"
              
  VirtualRouter:
    Type: AWS::AppMesh::VirtualRouter
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualRouterName: virtual-router
      Spec:
        Listeners:
        - PortMapping:
            Port: 80
            Protocol: http

  VirtualService:
    DependsOn:
     - VirtualRouter
    Type: AWS::AppMesh::VirtualService
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualServiceName: !Sub 'backend.${ProjectName}.local'
      Spec:
        Provider:
          VirtualRouter:
            VirtualRouterName: virtual-router

  Route:
    DependsOn:
     - VirtualRouter
     - BackendNode
    Type: AWS::AppMesh::Route
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualRouterName: virtual-router
      RouteName: route
      Spec:
        HttpRoute:
          Action:
            WeightedTargets:
            - VirtualNode: backend-1
              Weight: 1
          Match:
            Prefix: /
