Parameters:

  GatewayImageName:
    Description: The name for the gateway image
    Type: String

  ColorTellerImageName:
    Description: The name for the color teller image
    Type: String

Resources:
  GatewayRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref GatewayImageName

  ColorTellerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ColorTellerImageName

  ColorTellerEnvoyImageName:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${ColorTellerImageName}-envoy"
