// Code generated by protoc-gen-go. DO NOT EDIT.
// source: color.proto

package color

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Color int32

const (
	Color_NO_COLOR Color = 0
	Color_RED      Color = 1
	Color_BLUE     Color = 2
	Color_GREEN    Color = 3
	Color_YELLOW   Color = 4
	Color_ORANGE   Color = 5
	Color_PURPLE   Color = 6
	Color_PINK     Color = 7
	Color_BLACK    Color = 8
	Color_WHITE    Color = 9
)

var Color_name = map[int32]string{
	0: "NO_COLOR",
	1: "RED",
	2: "BLUE",
	3: "GREEN",
	4: "YELLOW",
	5: "ORANGE",
	6: "PURPLE",
	7: "PINK",
	8: "BLACK",
	9: "WHITE",
}

var Color_value = map[string]int32{
	"NO_COLOR": 0,
	"RED":      1,
	"BLUE":     2,
	"GREEN":    3,
	"YELLOW":   4,
	"ORANGE":   5,
	"PURPLE":   6,
	"PINK":     7,
	"BLACK":    8,
	"WHITE":    9,
}

func (x Color) String() string {
	return proto.EnumName(Color_name, int32(x))
}

func (Color) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83c7eb30498dece0, []int{0}
}

type GetColorRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetColorRequest) Reset()         { *m = GetColorRequest{} }
func (m *GetColorRequest) String() string { return proto.CompactTextString(m) }
func (*GetColorRequest) ProtoMessage()    {}
func (*GetColorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83c7eb30498dece0, []int{0}
}

func (m *GetColorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetColorRequest.Unmarshal(m, b)
}
func (m *GetColorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetColorRequest.Marshal(b, m, deterministic)
}
func (m *GetColorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetColorRequest.Merge(m, src)
}
func (m *GetColorRequest) XXX_Size() int {
	return xxx_messageInfo_GetColorRequest.Size(m)
}
func (m *GetColorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetColorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetColorRequest proto.InternalMessageInfo

type GetColorResponse struct {
	Color                Color    `protobuf:"varint,1,opt,name=color,proto3,enum=color.Color" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetColorResponse) Reset()         { *m = GetColorResponse{} }
func (m *GetColorResponse) String() string { return proto.CompactTextString(m) }
func (*GetColorResponse) ProtoMessage()    {}
func (*GetColorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83c7eb30498dece0, []int{1}
}

func (m *GetColorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetColorResponse.Unmarshal(m, b)
}
func (m *GetColorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetColorResponse.Marshal(b, m, deterministic)
}
func (m *GetColorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetColorResponse.Merge(m, src)
}
func (m *GetColorResponse) XXX_Size() int {
	return xxx_messageInfo_GetColorResponse.Size(m)
}
func (m *GetColorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetColorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetColorResponse proto.InternalMessageInfo

func (m *GetColorResponse) GetColor() Color {
	if m != nil {
		return m.Color
	}
	return Color_NO_COLOR
}

type SetColorRequest struct {
	Color                Color    `protobuf:"varint,1,opt,name=color,proto3,enum=color.Color" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetColorRequest) Reset()         { *m = SetColorRequest{} }
func (m *SetColorRequest) String() string { return proto.CompactTextString(m) }
func (*SetColorRequest) ProtoMessage()    {}
func (*SetColorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83c7eb30498dece0, []int{2}
}

func (m *SetColorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetColorRequest.Unmarshal(m, b)
}
func (m *SetColorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetColorRequest.Marshal(b, m, deterministic)
}
func (m *SetColorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetColorRequest.Merge(m, src)
}
func (m *SetColorRequest) XXX_Size() int {
	return xxx_messageInfo_SetColorRequest.Size(m)
}
func (m *SetColorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetColorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetColorRequest proto.InternalMessageInfo

func (m *SetColorRequest) GetColor() Color {
	if m != nil {
		return m.Color
	}
	return Color_NO_COLOR
}

type SetColorResponse struct {
	Color                Color    `protobuf:"varint,1,opt,name=color,proto3,enum=color.Color" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetColorResponse) Reset()         { *m = SetColorResponse{} }
func (m *SetColorResponse) String() string { return proto.CompactTextString(m) }
func (*SetColorResponse) ProtoMessage()    {}
func (*SetColorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83c7eb30498dece0, []int{3}
}

func (m *SetColorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetColorResponse.Unmarshal(m, b)
}
func (m *SetColorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetColorResponse.Marshal(b, m, deterministic)
}
func (m *SetColorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetColorResponse.Merge(m, src)
}
func (m *SetColorResponse) XXX_Size() int {
	return xxx_messageInfo_SetColorResponse.Size(m)
}
func (m *SetColorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetColorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetColorResponse proto.InternalMessageInfo

func (m *SetColorResponse) GetColor() Color {
	if m != nil {
		return m.Color
	}
	return Color_NO_COLOR
}

func init() {
	proto.RegisterEnum("color.Color", Color_name, Color_value)
	proto.RegisterType((*GetColorRequest)(nil), "color.GetColorRequest")
	proto.RegisterType((*GetColorResponse)(nil), "color.GetColorResponse")
	proto.RegisterType((*SetColorRequest)(nil), "color.SetColorRequest")
	proto.RegisterType((*SetColorResponse)(nil), "color.SetColorResponse")
}

func init() { proto.RegisterFile("color.proto", fileDescriptor_83c7eb30498dece0) }

var fileDescriptor_83c7eb30498dece0 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xce, 0xcf, 0xc9,
	0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x04, 0xb9, 0xf8, 0xdd,
	0x53, 0x4b, 0x9c, 0x41, 0xec, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x25, 0x33, 0x2e, 0x01,
	0x84, 0x50, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x12, 0x17, 0x44, 0xbd, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x9f, 0x11, 0x8f, 0x1e, 0xc4, 0x28, 0x88, 0x22, 0xa8, 0x51, 0xa6, 0x5c, 0xfc, 0xc1,
	0xa8, 0x46, 0x11, 0xa5, 0xcd, 0x8c, 0x4b, 0x20, 0x98, 0x0c, 0xeb, 0xb4, 0xca, 0xb9, 0x58, 0xc1,
	0x7c, 0x21, 0x1e, 0x2e, 0x0e, 0x3f, 0xff, 0x78, 0x67, 0x7f, 0x1f, 0xff, 0x20, 0x01, 0x06, 0x21,
	0x76, 0x2e, 0xe6, 0x20, 0x57, 0x17, 0x01, 0x46, 0x21, 0x0e, 0x2e, 0x16, 0x27, 0x9f, 0x50, 0x57,
	0x01, 0x26, 0x21, 0x4e, 0x2e, 0x56, 0xf7, 0x20, 0x57, 0x57, 0x3f, 0x01, 0x66, 0x21, 0x2e, 0x2e,
	0xb6, 0x48, 0x57, 0x1f, 0x1f, 0xff, 0x70, 0x01, 0x16, 0x10, 0xdb, 0x3f, 0xc8, 0xd1, 0xcf, 0xdd,
	0x55, 0x80, 0x15, 0xc4, 0x0e, 0x08, 0x0d, 0x0a, 0xf0, 0x71, 0x15, 0x60, 0x03, 0x69, 0x0c, 0xf0,
	0xf4, 0xf3, 0x16, 0x60, 0x07, 0x69, 0x74, 0xf2, 0x71, 0x74, 0xf6, 0x16, 0xe0, 0x00, 0x31, 0xc3,
	0x3d, 0x3c, 0x43, 0x5c, 0x05, 0x38, 0x8d, 0x7a, 0x18, 0xb9, 0x78, 0xc0, 0x36, 0x07, 0xa7, 0x16,
	0x95, 0x65, 0x26, 0xa7, 0x0a, 0xd9, 0x72, 0x71, 0xc0, 0x02, 0x4c, 0x48, 0x0c, 0xea, 0x54, 0xb4,
	0x40, 0x95, 0x12, 0xc7, 0x10, 0x87, 0x78, 0x55, 0x89, 0x01, 0xa4, 0x3d, 0x18, 0x5d, 0x7b, 0x30,
	0x0e, 0xed, 0xc1, 0x18, 0xda, 0x93, 0xd8, 0xc0, 0xf1, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x42, 0x63, 0xf3, 0xd5, 0xde, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ColorServiceClient is the client API for ColorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ColorServiceClient interface {
	GetColor(ctx context.Context, in *GetColorRequest, opts ...grpc.CallOption) (*GetColorResponse, error)
	SetColor(ctx context.Context, in *SetColorRequest, opts ...grpc.CallOption) (*SetColorResponse, error)
}

type colorServiceClient struct {
	cc *grpc.ClientConn
}

func NewColorServiceClient(cc *grpc.ClientConn) ColorServiceClient {
	return &colorServiceClient{cc}
}

func (c *colorServiceClient) GetColor(ctx context.Context, in *GetColorRequest, opts ...grpc.CallOption) (*GetColorResponse, error) {
	out := new(GetColorResponse)
	err := c.cc.Invoke(ctx, "/color.ColorService/GetColor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colorServiceClient) SetColor(ctx context.Context, in *SetColorRequest, opts ...grpc.CallOption) (*SetColorResponse, error) {
	out := new(SetColorResponse)
	err := c.cc.Invoke(ctx, "/color.ColorService/SetColor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ColorServiceServer is the server API for ColorService service.
type ColorServiceServer interface {
	GetColor(context.Context, *GetColorRequest) (*GetColorResponse, error)
	SetColor(context.Context, *SetColorRequest) (*SetColorResponse, error)
}

// UnimplementedColorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedColorServiceServer struct {
}

func (*UnimplementedColorServiceServer) GetColor(ctx context.Context, req *GetColorRequest) (*GetColorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetColor not implemented")
}
func (*UnimplementedColorServiceServer) SetColor(ctx context.Context, req *SetColorRequest) (*SetColorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetColor not implemented")
}

func RegisterColorServiceServer(s *grpc.Server, srv ColorServiceServer) {
	s.RegisterService(&_ColorService_serviceDesc, srv)
}

func _ColorService_GetColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorServiceServer).GetColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/color.ColorService/GetColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorServiceServer).GetColor(ctx, req.(*GetColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColorService_SetColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorServiceServer).SetColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/color.ColorService/SetColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorServiceServer).SetColor(ctx, req.(*SetColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ColorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "color.ColorService",
	HandlerType: (*ColorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetColor",
			Handler:    _ColorService_GetColor_Handler,
		},
		{
			MethodName: "SetColor",
			Handler:    _ColorService_SetColor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "color.proto",
}
