// Code generated by protoc-gen-go. DO NOT EDIT.
// source: color.proto

package color

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetColorRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetColorRequest) Reset()         { *m = GetColorRequest{} }
func (m *GetColorRequest) String() string { return proto.CompactTextString(m) }
func (*GetColorRequest) ProtoMessage()    {}
func (*GetColorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83c7eb30498dece0, []int{0}
}

func (m *GetColorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetColorRequest.Unmarshal(m, b)
}
func (m *GetColorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetColorRequest.Marshal(b, m, deterministic)
}
func (m *GetColorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetColorRequest.Merge(m, src)
}
func (m *GetColorRequest) XXX_Size() int {
	return xxx_messageInfo_GetColorRequest.Size(m)
}
func (m *GetColorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetColorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetColorRequest proto.InternalMessageInfo

type GetColorResponse struct {
	Color                string   `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetColorResponse) Reset()         { *m = GetColorResponse{} }
func (m *GetColorResponse) String() string { return proto.CompactTextString(m) }
func (*GetColorResponse) ProtoMessage()    {}
func (*GetColorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83c7eb30498dece0, []int{1}
}

func (m *GetColorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetColorResponse.Unmarshal(m, b)
}
func (m *GetColorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetColorResponse.Marshal(b, m, deterministic)
}
func (m *GetColorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetColorResponse.Merge(m, src)
}
func (m *GetColorResponse) XXX_Size() int {
	return xxx_messageInfo_GetColorResponse.Size(m)
}
func (m *GetColorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetColorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetColorResponse proto.InternalMessageInfo

func (m *GetColorResponse) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

type SetColorRequest struct {
	Color                string   `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetColorRequest) Reset()         { *m = SetColorRequest{} }
func (m *SetColorRequest) String() string { return proto.CompactTextString(m) }
func (*SetColorRequest) ProtoMessage()    {}
func (*SetColorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83c7eb30498dece0, []int{2}
}

func (m *SetColorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetColorRequest.Unmarshal(m, b)
}
func (m *SetColorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetColorRequest.Marshal(b, m, deterministic)
}
func (m *SetColorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetColorRequest.Merge(m, src)
}
func (m *SetColorRequest) XXX_Size() int {
	return xxx_messageInfo_SetColorRequest.Size(m)
}
func (m *SetColorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetColorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetColorRequest proto.InternalMessageInfo

func (m *SetColorRequest) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

type SetColorResponse struct {
	Color                string   `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetColorResponse) Reset()         { *m = SetColorResponse{} }
func (m *SetColorResponse) String() string { return proto.CompactTextString(m) }
func (*SetColorResponse) ProtoMessage()    {}
func (*SetColorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83c7eb30498dece0, []int{3}
}

func (m *SetColorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetColorResponse.Unmarshal(m, b)
}
func (m *SetColorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetColorResponse.Marshal(b, m, deterministic)
}
func (m *SetColorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetColorResponse.Merge(m, src)
}
func (m *SetColorResponse) XXX_Size() int {
	return xxx_messageInfo_SetColorResponse.Size(m)
}
func (m *SetColorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetColorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetColorResponse proto.InternalMessageInfo

func (m *SetColorResponse) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func init() {
	proto.RegisterType((*GetColorRequest)(nil), "color.GetColorRequest")
	proto.RegisterType((*GetColorResponse)(nil), "color.GetColorResponse")
	proto.RegisterType((*SetColorRequest)(nil), "color.SetColorRequest")
	proto.RegisterType((*SetColorResponse)(nil), "color.SetColorResponse")
}

func init() { proto.RegisterFile("color.proto", fileDescriptor_83c7eb30498dece0) }

var fileDescriptor_83c7eb30498dece0 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xce, 0xcf, 0xc9,
	0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x04, 0xb9, 0xf8, 0xdd,
	0x53, 0x4b, 0x9c, 0x41, 0xec, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x25, 0x0d, 0x2e, 0x01,
	0x84, 0x50, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x08, 0x17, 0x44, 0xbd, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x54, 0xb3, 0x3a, 0x17, 0x7f, 0x30, 0xaa, 0x66, 0x1c, 0x0a, 0x35, 0xb8,
	0x04, 0x82, 0x89, 0x32, 0xd2, 0xa8, 0x87, 0x91, 0x8b, 0x07, 0xac, 0x2e, 0x38, 0xb5, 0xa8, 0x2c,
	0x33, 0x39, 0x55, 0xc8, 0x96, 0x8b, 0x03, 0xe6, 0x1a, 0x21, 0x31, 0x3d, 0x88, 0x0f, 0xd0, 0x5c,
	0x2c, 0x25, 0x8e, 0x21, 0x0e, 0xb1, 0x43, 0x89, 0x01, 0xa4, 0x3d, 0x18, 0x5d, 0x7b, 0x30, 0x0e,
	0xed, 0xc1, 0x18, 0xda, 0x93, 0xd8, 0xc0, 0x81, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa5,
	0x53, 0xbf, 0x24, 0x3b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ColorServiceClient is the client API for ColorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ColorServiceClient interface {
	GetColor(ctx context.Context, in *GetColorRequest, opts ...grpc.CallOption) (*GetColorResponse, error)
	SetColor(ctx context.Context, in *SetColorRequest, opts ...grpc.CallOption) (*SetColorResponse, error)
}

type colorServiceClient struct {
	cc *grpc.ClientConn
}

func NewColorServiceClient(cc *grpc.ClientConn) ColorServiceClient {
	return &colorServiceClient{cc}
}

func (c *colorServiceClient) GetColor(ctx context.Context, in *GetColorRequest, opts ...grpc.CallOption) (*GetColorResponse, error) {
	out := new(GetColorResponse)
	err := c.cc.Invoke(ctx, "/color.ColorService/GetColor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colorServiceClient) SetColor(ctx context.Context, in *SetColorRequest, opts ...grpc.CallOption) (*SetColorResponse, error) {
	out := new(SetColorResponse)
	err := c.cc.Invoke(ctx, "/color.ColorService/SetColor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ColorServiceServer is the server API for ColorService service.
type ColorServiceServer interface {
	GetColor(context.Context, *GetColorRequest) (*GetColorResponse, error)
	SetColor(context.Context, *SetColorRequest) (*SetColorResponse, error)
}

// UnimplementedColorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedColorServiceServer struct {
}

func (*UnimplementedColorServiceServer) GetColor(ctx context.Context, req *GetColorRequest) (*GetColorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetColor not implemented")
}
func (*UnimplementedColorServiceServer) SetColor(ctx context.Context, req *SetColorRequest) (*SetColorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetColor not implemented")
}

func RegisterColorServiceServer(s *grpc.Server, srv ColorServiceServer) {
	s.RegisterService(&_ColorService_serviceDesc, srv)
}

func _ColorService_GetColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorServiceServer).GetColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/color.ColorService/GetColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorServiceServer).GetColor(ctx, req.(*GetColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColorService_SetColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorServiceServer).SetColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/color.ColorService/SetColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorServiceServer).SetColor(ctx, req.(*SetColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ColorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "color.ColorService",
	HandlerType: (*ColorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetColor",
			Handler:    _ColorService_GetColor_Handler,
		},
		{
			MethodName: "SetColor",
			Handler:    _ColorService_SetColor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "color.proto",
}
