apiVersion: v1
kind: Service
metadata:
  name: dj
  namespace: prod
  labels:
    app: dj
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: dj
---
apiVersion: v1
kind: Service
metadata:
  name: metal-v1
  namespace: prod
  labels:
    app: metal
    version: v1
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: metal
    version: v1

---
apiVersion: v1
kind: Service
metadata:
  name: jazz-v1
  namespace: prod
  labels:
    app: jazz
    version: v1
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: jazz
    version: v1
