---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    mesh: yelb
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
  name: yelb
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: yelb
spec:
  namespaceSelector:
    matchLabels:
      mesh: yelb
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: redis-server-NEW
  namespace: yelb
spec:
  awsName: redis-server-NEW-virtual-node
  podSelector:
    matchLabels:
      app: redis-server
      version: "NEW"
  listeners:
    - portMapping:
        port: 6379
        protocol: tcp
      healthCheck:
        healthyThreshold: 2
        intervalMillis: 5000
        port: 6379
        protocol: tcp
        timeoutMillis: 2000
        unhealthyThreshold: 2
  logging:
    accessLog:
      file:
        path: /dev/stdout
  serviceDiscovery:
    dns:
      hostname: redis-server-NEW.yelb.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: yelb
  name: redis-server
spec:
  awsName: redis-server-virtual-router
  listeners:
    - portMapping:
        port: 6379
        protocol: tcp
  routes:
    - name: route-to-redis-server
      tcpRoute:
        match:
          prefix: /
        action:
          weightedTargets: [CANARY_DEPLOYMENT]
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: redis-server
  namespace: yelb
spec:
  awsName: redis-server
  provider:
    virtualRouter:
        virtualRouterRef:
            name: redis-server
---
apiVersion: v1
kind: Service
metadata:
  namespace: yelb
  name: redis-server-NEW
  labels:
    app: redis-server
    version: "NEW"
    tier: cache
spec:
  type: ClusterIP
  ports:
    - port: 6379
      name: tcp
  selector:
    app: redis-server
    version: "NEW"
    tier: cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yelb
  name: redis-server-NEW
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
      version: "NEW"
      tier: cache
  template:
    metadata:
      labels:
        app: redis-server
        version: "NEW"
        tier: cache
    spec:
      containers:
        - name: redis-server
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  namespace: yelb
  name: redis-server # used to provide a DNS entry for yelb-appserver VS
spec:
  ports:
    - port: 6379
      name: tcp