version: '2.2'

networks:
  test_net:
    driver: bridge

services:

  sut:
    image: vote-votes
    entrypoint: node_modules/mocha/bin/mocha --ui tdd test/test.js 
    environment:
      - DATABASE_NAME=votes_test_db
    networks:
      - test_net
    depends_on:
      - votes

  votes:
    build: .
    image: vote-votes
    environment:
      - DATABASE_NAME=votes_test_db
    networks:
      - test_net
    depends_on:
      - reports
      - queue
      - worker

  reports:
    image: subfuzion/vote-reports
    environment:
      - DATABASE_NAME=votes_test_db
    networks:
      - test_net
    depends_on:
      - database

  worker:
    image: subfuzion/vote-worker
    environment:
      - DATABASE_NAME=votes_test_db
    networks:
      - test_net
    depends_on:
      - database
      - queue

  database:
    image: mongo:3.6
    networks:
      - test_net

  queue:
    image: redis:3.2
    networks:
      - test_net

