---
apiVersion: v1
kind: Service
metadata:
  name: cats
  labels:
    name: cats
  namespace: appmesh-demo
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: cats
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cats
  namespace: appmesh-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cats
      annotations:
        appmesh.amazon.com/ports: "80"
        appmesh.amazon.com/virtualNode: "cats"
        appmesh.k8s.aws/mesh: demo-mesh
    spec:
      containers:
      - name: cats
        image: 072792469044.dkr.ecr.eu-west-1.amazonaws.com/meshdemo-cats:0.1.0-beta
        ports:
        - containerPort: 80
