---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: appmesh-demo
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    name: front-end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: appmesh-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: 072792469044.dkr.ecr.eu-west-1.amazonaws.com/meshdemo-frontend:0.1.0-beta
        ports:
        - containerPort: 8000
        args: ["--rewrite", "/cats -> http://cats", "--rewrite", "/colors -> http://colors:8080"]

