Parameters:

  FrontendImageName:
    Description: The name for the Frontend image
    Type: String

  ColorTellerImageName:
    Description: The name for the color teller backend image
    Type: String
  
  ColorAppEnvoyImageName:
    Description: The name for the color app envoy image
    Type: String

Resources:
  FrontendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref FrontendImageName

  ColorTellerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ColorTellerImageName

  ColorTellerEnvoyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ColorAppEnvoyImageName
