apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Database.Component }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  selector:
    app: database
  ports:
  - port: {{ .Values.Database.ServicePort }}
    targetPort: {{ .Values.Database.ContainerPortName }}
