apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "queue-fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Queue.Component }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ default 1 .Values.Queue.Replicas }}
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: "{{ .Values.Queue.Image }}:{{ .Values.Queue.ImageTag }}"
        ports:
        - containerPort: {{ .Values.Queue.ContainerPort }}
          name: {{ .Values.Queue.ContainerPortName }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - '[ $(redis-cli ping) = PONG ]'
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 5
