apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Vote.Component }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  type: {{ .Values.Vote.ServiceType }}
  selector:
    app: vote
  ports:
  - port: {{ .Values.Vote.ServicePort }}
    targetPort: {{ .Values.Vote.ContainerPortName }}
