---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    mesh: yelb
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
  name: yelb
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: yelb
spec:
  namespaceSelector:
    matchLabels:
      mesh: yelb
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: yelb-appserver-CANARY_VERSION
  namespace: yelb
spec:
  awsName: yelb-appserver-CANARY_VERSION-virtual-node
  podSelector:
    matchLabels:
      app: yelb-appserver
      version: "CANARY_VERSION"
  listeners:
    - portMapping:
        port: 4567
        protocol: http
      healthCheck:
        healthyThreshold: 2
        intervalMillis: 5000
        path: "/api/hostname"
        port: 4567
        protocol: "http"
        timeoutMillis: 2000
        unhealthyThreshold: 2
  logging:
    accessLog:
      file:
        path: /dev/stdout
  serviceDiscovery:
    dns:
      hostname: yelb-appserver-CANARY_VERSION.yelb.svc.cluster.local
  backends:
    - virtualService:
       virtualServiceRef:
          name: yelb-db
    - virtualService:
       virtualServiceRef:
          name: redis-server
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: yelb
  name: yelb-appserver
spec:
  awsName: yelb-appserver-virtual-router
  listeners:
    - portMapping:
        port: 4567
        protocol: http
  routes:
    - name: route-to-yelb-appserver
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets: [CANARY_ROUTES]
        retryPolicy:
            maxRetries: 2
            perRetryTimeout:
                unit: ms
                value: 2000
            httpRetryEvents:
                - server-error
                - client-error
                - gateway-error
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: yelb-appserver
  namespace: yelb
spec:
  awsName: yelb-appserver
  provider:
    virtualRouter:
        virtualRouterRef:
            name: yelb-appserver
---
apiVersion: v1
kind: Service
metadata:
  namespace: yelb
  name: yelb-appserver-CANARY_VERSION
  labels:
    app: yelb-appserver
    version: "CANARY_VERSION"
    tier: middletier
spec:
  type: ClusterIP
  ports:
    - port: 4567
      name: http
  selector:
    app: yelb-appserver
    version: "CANARY_VERSION"
    tier: middletier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yelb
  name: yelb-appserver-CANARY_VERSION
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelb-appserver
      version: "CANARY_VERSION"
      tier: middletier
  template:
    metadata:
      labels:
        app: yelb-appserver
        version: "CANARY_VERSION"
        tier: middletier
    spec:
      containers:
        - name: yelb-appserver
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  namespace: yelb
  name: yelb-appserver # used to provide a DNS entry for yelb-appserver VS
spec:
  ports:
    - port: 4567
      name: http