version: '2.2'

networks:
  test_net:
    driver: bridge
  votes_net:
    driver: bridge
  reports_net:
    driver: bridge
  db_net:
    driver: bridge
services:

  sut:
    image: web
    entrypoint: node_modules/mocha/bin/mocha --ui tdd test/test.js 
    environment:
      - DATABASE_NAME=vote_test_db
    networks:
      - test_net
      - db_net
    depends_on:
      - web

  web:
    build: .
    image: web
    environment:
      - DATABASE_NAME=vote_test_db
    networks:
      - test_net
      - votes_net
      - reports_net
    depends_on:
      - votes
      - reports

  votes:
    image: subfuzion/vote-votes
    environment:
      - DATABASE_NAME=vote_test_db
    networks:
      - votes_net
      - db_net
    depends_on:
      - queue
      - worker

  reports:
    image: subfuzion/vote-reports
    environment:
      - DATABASE_NAME=vote_test_db
    networks:
      - reports_net
      - db_net
    depends_on:
      - database

  worker:
    image: subfuzion/vote-worker
    environment:
      - DATABASE_NAME=vote_test_db
    networks:
      - votes_net
      - db_net
    depends_on:
      - database
      - queue

  database:
    image: mongo:3.6
    networks:
      - db_net

  queue:
    image: redis:3.2
    networks:
      - votes_net
